//! Corpus discovery: turning "some seeded database" into the concrete ids the
//! case catalogue binds to.
//!
//! Every probe is **deterministic** — each orders by a total key so the same
//! corpus always yields the same ids, and therefore the same query plans and
//! the same comparable numbers. A probe that picked "any row" would make the
//! run-to-run variance of the baseline gate unattributable.
//!
//! Probes are not timed and are allowed to be slow. Several of them aggregate
//! over the whole `task` table, which at the reference corpus is a scan taking
//! seconds. That cost is paid once per run and appears in no sample.

use crate::db::Session;
use crate::report::Corpus;
use anyhow::{Context, Result, bail};

/// Upper bound on the accessible-project array bound into the search case.
/// `docs/30` §Known scaling limits puts the redesign threshold at ~2,000
/// projects per actor; a benchmark that quietly bound 2,000 uuids would be
/// measuring the escape hatch rather than the design.
const MAX_ACCESSIBLE_PROJECTS: usize = 200;

#[derive(Debug)]
pub struct Fixtures {
    pub corpus: Corpus,
    /// Caveats worth carrying into the report — a fallback that was taken, a
    /// list that was truncated.
    pub notes: Vec<String>,
}

/// Discover the workspace to measure. Deliberately the oldest workspace when
/// unspecified: a corpus with more than one workspace should be measured with
/// `--workspace` given explicitly, and picking the oldest at least picks the
/// same one every time.
pub fn resolve_workspace(session: &mut Session, requested: Option<&str>) -> Result<String> {
    if let Some(id) = requested {
        let found = session
            .fetch_scalar(&format!(
                "SELECT id FROM workspace WHERE id = '{}'::uuid AND deleted_at IS NULL",
                escape_uuid(id)?
            ))
            .context("looking up the requested workspace")?;
        return found.ok_or_else(|| {
            anyhow::anyhow!("workspace {id} does not exist, or is soft-deleted, in this database")
        });
    }
    session
        .fetch_scalar(
            "SELECT id FROM workspace WHERE deleted_at IS NULL ORDER BY created_at, id LIMIT 1",
        )?
        .ok_or_else(|| {
            anyhow::anyhow!(
                "no workspace in this database. The reference corpus is generated by \
                 tools/casual-task-seed (F-006); this harness measures a corpus, it does \
                 not create one."
            )
        })
}

/// Bind every `psql` variable the catalogue references, and describe the corpus
/// that was found. The session must already be scoped to `workspace_id`.
pub fn bind(
    session: &mut Session,
    workspace_id: &str,
    scale: &str,
    search_term: &str,
) -> Result<Fixtures> {
    let mut notes = Vec::new();
    session.set_var("workspace_id", workspace_id)?;
    session.set_var("search_term", search_term)?;

    let tasks = count(
        session,
        "SELECT count(*) FROM task WHERE deleted_at IS NULL",
    )?;
    if tasks == 0 {
        bail!(
            "workspace {workspace_id} contains no tasks. Seed a corpus first \
             (tools/casual-task-seed, F-006) — measuring an empty corpus produces \
             numbers that look excellent and mean nothing."
        );
    }
    let projects = count(
        session,
        "SELECT count(*) FROM project WHERE deleted_at IS NULL",
    )?;
    let users = count(session, "SELECT count(*) FROM workspace_membership")?;
    let search_documents = count(session, "SELECT count(*) FROM task_search")?;
    let activity_events = count(session, "SELECT count(*) FROM activity_event")?;

    if search_documents == 0 {
        notes.push(
            "task_search is empty: the full_text_search case returns no rows and its \
             number is not a search measurement. The projection is maintained by the \
             outbox worker (docs/26), which is Phase 1."
                .to_owned(),
        );
    }
    if activity_events == 0 {
        notes.push("activity_event is empty: the activity_page case returns no rows.".to_owned());
    }

    // The busiest project — the one whose board and list pages are worth
    // measuring. Ties break on id so the choice is total.
    let project_id = require(
        session,
        "SELECT t.project_id
           FROM task t
          WHERE t.deleted_at IS NULL
          GROUP BY t.project_id
          ORDER BY count(*) DESC, t.project_id
          LIMIT 1",
        "busiest project",
    )?;
    session.set_var("project_id", &project_id)?;

    let status_id = require(
        session,
        "SELECT t.status_id
           FROM task t
          WHERE t.project_id = :'project_id'::uuid AND t.deleted_at IS NULL
          GROUP BY t.status_id
          ORDER BY count(*) DESC, t.status_id
          LIMIT 1",
        "busiest board column",
    )?;
    session.set_var("status_id", &status_id)?;

    // A task from the middle of the project's numbering rather than its first:
    // the first task of a project is atypical (no parent, few events, often the
    // template row a seeder writes differently).
    let task_row = row(
        session,
        "SELECT t.id, t.number
           FROM task t
          WHERE t.project_id = :'project_id'::uuid
            AND t.deleted_at IS NULL
            AND t.number >= (SELECT max(number) / 2 FROM task WHERE project_id = :'project_id'::uuid)
          ORDER BY t.number
          LIMIT 1",
    )?
    .context("no task found in the busiest project")?;
    let (task_id, task_number) = two(&task_row, "task id and number")?;
    session.set_var("task_id", &task_id)?;
    session.set_var("task_number", &task_number)?;

    // The newest row of the list view, used as the cursor so the measured page
    // is a real second page rather than the head of the index.
    let cursor_row = row(
        session,
        "SELECT t.updated_at, t.id
           FROM task t
          WHERE t.project_id = :'project_id'::uuid AND t.deleted_at IS NULL
          ORDER BY t.updated_at DESC, t.id DESC
          LIMIT 1",
    )?
    .context("no cursor row found in the busiest project")?;
    let (cursor_updated_at, cursor_id) = two(&cursor_row, "cursor key")?;
    session.set_var("cursor_updated_at", &cursor_updated_at)?;
    session.set_var("cursor_id", &cursor_id)?;

    // The actor: whoever carries the most assigned work. A user with no
    // assignments would make my_work_assigned measure an empty result.
    let user_id = match session.fetch_scalar(
        "SELECT a.user_id
           FROM task_assignee a
          GROUP BY a.user_id
          ORDER BY count(*) DESC, a.user_id
          LIMIT 1",
    )? {
        Some(id) => id,
        None => {
            notes.push(
                "no task_assignee rows: the actor was chosen from workspace_membership and \
                 my_work_assigned returns no rows."
                    .to_owned(),
            );
            require(
                session,
                "SELECT m.user_id FROM workspace_membership m ORDER BY m.user_id LIMIT 1",
                "workspace member",
            )?
        }
    };
    session.set_var("user_id", &user_id)?;

    let accessible = accessible_projects(session, &mut notes)?;
    session.set_var("accessible_projects", &accessible)?;

    Ok(Fixtures {
        corpus: Corpus {
            scale: scale.to_owned(),
            workspace_id: workspace_id.to_owned(),
            tasks,
            projects,
            users,
            search_documents,
            activity_events,
        },
        notes,
    })
}

/// The actor's accessible project set, as a PostgreSQL array literal.
///
/// Falls back to every project in the workspace when the corpus carries no
/// grants, because a search case bound to an empty array measures an empty
/// result. The fallback is recorded as a note rather than hidden: it changes
/// what the number means.
fn accessible_projects(session: &mut Session, notes: &mut Vec<String>) -> Result<String> {
    let granted = session.fetch_column(
        "SELECT DISTINCT p.id
           FROM project p
           JOIN role_assignment ra
             ON ra.workspace_id = p.workspace_id
            AND ((ra.scope_type = 'PROJECT' AND ra.scope_id = p.id)
              OR (ra.scope_type = 'WORKSPACE' AND ra.scope_id = p.workspace_id))
          WHERE p.deleted_at IS NULL
            AND ra.principal_type = 'USER'
            AND ra.principal_id = :'user_id'::uuid
          ORDER BY 1",
    )?;

    let mut ids = if granted.is_empty() {
        notes.push(
            "the chosen actor holds no role assignment: accessible_projects fell back to \
             every project in the workspace, so full_text_search measures an unfiltered \
             permission pre-filter."
                .to_owned(),
        );
        session
            .fetch_column("SELECT p.id FROM project p WHERE p.deleted_at IS NULL ORDER BY p.id")?
    } else {
        granted
    };

    if ids.len() > MAX_ACCESSIBLE_PROJECTS {
        notes.push(format!(
            "accessible_projects truncated from {} to {MAX_ACCESSIBLE_PROJECTS} \
             (docs/30 §Known scaling limits).",
            ids.len()
        ));
        ids.truncate(MAX_ACCESSIBLE_PROJECTS);
    }
    if ids.is_empty() {
        bail!("no projects in this workspace");
    }
    Ok(format!("{{{}}}", ids.join(",")))
}

fn count(session: &mut Session, sql: &str) -> Result<i64> {
    let raw = require(session, sql, "count")?;
    raw.parse()
        .with_context(|| format!("parsing count `{raw}`"))
}

fn require(session: &mut Session, sql: &str, what: &str) -> Result<String> {
    session
        .fetch_scalar(sql)?
        .ok_or_else(|| anyhow::anyhow!("corpus probe for {what} returned no row"))
}

fn row(session: &mut Session, sql: &str) -> Result<Option<Vec<String>>> {
    Ok(session
        .fetch_scalar(sql)?
        .map(|line| line.split('|').map(str::to_owned).collect()))
}

fn two(cols: &[String], what: &str) -> Result<(String, String)> {
    match cols {
        [a, b] => Ok((a.clone(), b.clone())),
        other => bail!("expected two columns for {what}, got {}", other.len()),
    }
}

/// Reject anything that is not a uuid before it reaches SQL text. The only
/// place a caller-supplied value is interpolated rather than bound, because
/// `psql` variables are not expanded inside the `\set` that would define them.
fn escape_uuid(value: &str) -> Result<String> {
    let parsed: uuid::Uuid = value
        .parse()
        .with_context(|| format!("`{value}` is not a uuid"))?;
    Ok(parsed.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn uuids_are_validated_before_reaching_sql() {
        assert!(escape_uuid("11111111-1111-7111-8111-111111111111").is_ok());
        assert!(escape_uuid("'; DROP TABLE task; --").is_err());
        assert!(escape_uuid("").is_err());
    }

    #[test]
    fn uuid_validation_normalises_case_and_braces() {
        assert_eq!(
            escape_uuid("{11111111-1111-7111-8111-11111111111A}").expect("uuid"),
            "11111111-1111-7111-8111-11111111111a"
        );
    }

    #[test]
    fn a_two_column_row_splits_into_its_parts() {
        let cols = vec!["2026-01-01 00:00:00+00".to_owned(), "abc".to_owned()];
        let (a, b) = two(&cols, "test").expect("two columns");
        assert_eq!(a, "2026-01-01 00:00:00+00");
        assert_eq!(b, "abc");
    }

    #[test]
    fn a_row_with_the_wrong_arity_is_an_error() {
        assert!(two(&["only".to_owned()], "test").is_err());
    }
}
