//! The loader: one `.sql` file that applies the corpus in foreign-key order.
//!
//! It is generated rather than hand-written so it cannot fall out of step with
//! the table list in `copy.rs` — the order the files are written, the order
//! they are named, and the order they are loaded all come from the same
//! declaration.

use std::collections::BTreeMap;
use std::fs;
use std::io::Write;
use std::path::Path;

use uuid::Uuid;

use crate::copy::{Table, format_ts};
use crate::scale::Plan;

pub const LOADER_FILE: &str = "load.sql";
pub const SCRIPT_FILE: &str = "load.sh";
pub const MANIFEST_FILE: &str = "manifest.json";

pub struct Summary<'a> {
    pub plan: &'a Plan,
    pub seed: u64,
    pub now: i64,
    pub workspace_id: Uuid,
    pub counts: &'a BTreeMap<&'static str, u64>,
}

impl std::fmt::Debug for Summary<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Summary")
            .field("seed", &self.seed)
            .field("scale", &self.plan.scale.as_str())
            .finish_non_exhaustive()
    }
}

pub fn write(dir: &Path, s: &Summary<'_>) -> std::io::Result<()> {
    write_loader(dir, s)?;
    write_script(dir)?;
    write_manifest(dir, s)
}

fn write_loader(dir: &Path, s: &Summary<'_>) -> std::io::Result<()> {
    let mut out = fs::File::create(dir.join(LOADER_FILE))?;
    writeln!(
        out,
        "\
-- TaskForge reference corpus — generated by tools/casual-task-seed.
--
--   scale     {scale}
--   seed      {seed}
--   clock     {now}
--   workspace {workspace}
--
-- Regenerate with:
--   cargo run -p casual-task-seed -- --scale {scale} --seed {seed} --out <dir>
--
-- Apply with psql, FROM THIS DIRECTORY (\\copy resolves relative paths against
-- the client's working directory, not against this file):
--
--   cd <dir> && psql \"$DATABASE_URL\" -v ON_ERROR_STOP=1 -f {loader}
--
-- or use the ./{script} wrapper, which does the cd for you.
--
-- WHICH ROLE LOADS THIS
--
-- Not `taskforge_app`. PostgreSQL rejects `COPY FROM` outright on any table
-- where row-level security applies to the current user — \"COPY FROM not
-- supported with row-level security\" — and migration 0010 FORCEs RLS on all
-- 30 tenant tables. That is not a policy this file can satisfy by setting
-- `taskforge.workspace_id`; the engine refuses before any policy is evaluated.
--
-- So the corpus is loaded by the same role that runs the migrations: a
-- superuser, or a role with BYPASSRLS. That is consistent with migration 0012,
-- which says migrations and the retention worker run as the owner while the
-- request-serving application never does. Loading a benchmark corpus is an
-- operator action of the same kind. The guard below turns the engine's
-- confusing message into this explanation.
--
-- Everything is one transaction: a corpus that half-loaded would be worse than
-- one that did not load at all, because the row counts would still look
-- plausible.

\\set ON_ERROR_STOP on
\\timing on

BEGIN;

DO $$
BEGIN
    IF row_security_active('task') THEN
        RAISE EXCEPTION 'casual-task-seed: this corpus must be loaded by a role '
            'that row-level security does not apply to (a superuser, or one with '
            'BYPASSRLS). PostgreSQL does not support COPY FROM into an '
            'RLS-protected table, and migration 0010 FORCEs RLS on every tenant '
            'table. Use the same role that applies the migrations.';
    END IF;
END $$;
",
        scale = s.plan.scale.as_str(),
        seed = s.seed,
        now = format_ts(s.now),
        workspace = s.workspace_id,
        loader = LOADER_FILE,
        script = SCRIPT_FILE,
    )?;

    for table in Table::ALL {
        let cols: Vec<String> = table
            .column_names()
            .iter()
            .map(|c| format!("\"{c}\""))
            .collect();
        let rows = s.counts.get(table.name()).copied().unwrap_or(0);
        writeln!(
            out,
            "\\echo '  {} ({} rows)'\n\\copy {} ({}) FROM '{}' WITH (FORMAT text)\n",
            table.name(),
            rows,
            table.name(),
            cols.join(","),
            table.file_name(),
        )?;
    }

    writeln!(
        out,
        "\
COMMIT;

-- Without statistics the planner has no idea what it received, and every
-- EXPLAIN assertion measured against this corpus would be measuring a default
-- estimate rather than the data (docs/26 §Index inventory). ANALYZE is part of
-- the load, not an optional follow-up.
\\echo 'ANALYZE (this is part of the load, not an extra)'
ANALYZE;
"
    )
}

fn write_script(dir: &Path) -> std::io::Result<()> {
    let path = dir.join(SCRIPT_FILE);
    let mut out = fs::File::create(&path)?;
    writeln!(
        out,
        "\
#!/usr/bin/env bash
# Load this corpus. Exists only to guarantee the working directory, which
# psql's \\copy resolves relative paths against.
#
#   ./{script} \"postgres://user:pass@host:5432/db\"
set -euo pipefail
cd \"$(dirname \"$0\")\"
psql \"${{1:-${{DATABASE_URL:?set DATABASE_URL or pass a DSN}}}}\" \\
  -v ON_ERROR_STOP=1 -f {loader}
",
        script = SCRIPT_FILE,
        loader = LOADER_FILE,
    )?;
    make_executable(&path)
}

#[cfg(unix)]
fn make_executable(path: &Path) -> std::io::Result<()> {
    use std::os::unix::fs::PermissionsExt;
    fs::set_permissions(path, fs::Permissions::from_mode(0o755))
}

#[cfg(not(unix))]
fn make_executable(_path: &Path) -> std::io::Result<()> {
    Ok(())
}

/// A machine-readable description of what was generated, for
/// `tools/casual-task-loadtest` to record alongside its measurements — a
/// benchmark number without the corpus it ran against is not comparable to
/// anything (docs/30 §Measurement).
fn write_manifest(dir: &Path, s: &Summary<'_>) -> std::io::Result<()> {
    let tables: Vec<serde_json::Value> = Table::ALL
        .iter()
        .map(|t| {
            serde_json::json!({
                "table": t.name(),
                "file": t.file_name(),
                "rows": s.counts.get(t.name()).copied().unwrap_or(0),
            })
        })
        .collect();
    let total: u64 = s.counts.values().sum();
    let doc = serde_json::json!({
        "generator": "casual-task-seed",
        "format": "postgresql-copy-text",
        "seed": s.seed,
        "scale": s.plan.scale.as_str(),
        "corpus_clock": format_ts(s.now),
        "workspace_id": s.workspace_id.to_string(),
        "planned": {
            "tasks": s.plan.tasks,
            "projects": s.plan.projects,
            "users": s.plan.users,
        },
        "total_rows": total,
        "tables": tables,
    });
    let mut out = fs::File::create(dir.join(MANIFEST_FILE))?;
    // Pretty-printed and newline-terminated so a `diff` between two runs of the
    // same seed is readable rather than a single enormous line.
    writeln!(out, "{}", serde_json::to_string_pretty(&doc)?)
}
