[package]
name = "casual-task-persistence"
version = "0.0.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
sqlx = { workspace = true }
casual-task-model = { workspace = true }
casual-task-search = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
time = { workspace = true }
uuid = { workspace = true }
casual-task-persistence = { path = "." }
tokio = { workspace = true }
sqlx = { workspace = true }
testcontainers = { workspace = true }
testcontainers-modules = { workspace = true }
anyhow = { workspace = true }
